/**
 * Mock asset data for selector page
 * This file contains sample data for development/testing purposes.
 * Replace this with actual data from your DAM API in production.
 */

const mockAssetData = [
    {
        id: "1",
        name: "hero-banner-desktop.jpg",
        previewUrl: "https://picsum.photos/1920/1080?random=1",
        thumbnailUrl: "https://picsum.photos/150/150?random=1",
        size: "3.2 MB",
        type: "JPEG",
        width: "1920",
        height: "1080",
        createdDate: "2024-01-15",
    },
    {
        id: "2",
        name: "product-catalog.pdf",
        previewUrl:
            "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
        thumbnailUrl: "https://via.placeholder.com/150x150/ff6b6b/ffffff?text=PDF",
        size: "1.8 MB",
        type: "PDF",
        width: "",
        height: "",
        createdDate: "2024-01-14",
    },
    {
        id: "3",
        name: "company-logo.svg",
        previewUrl: "https://via.placeholder.com/300x100/4ecdc4/ffffff?text=LOGO",
        thumbnailUrl: "https://via.placeholder.com/150x50/4ecdc4/ffffff?text=LOGO",
        size: "45 KB",
        type: "SVG",
        width: "300",
        height: "100",
        createdDate: "2024-01-13",
    },
    {
        id: "4",
        name: "team-photo-group.png",
        previewUrl: "https://picsum.photos/1200/800?random=4",
        thumbnailUrl: "https://picsum.photos/150/150?random=4",
        size: "4.1 MB",
        type: "PNG",
        width: "1200",
        height: "800",
        createdDate: "2024-01-12",
    },
    {
        id: "5",
        name: "presentation-slides.pptx",
        previewUrl: "https://via.placeholder.com/150x150/ff9ff3/ffffff?text=PPTX",
        thumbnailUrl: "https://via.placeholder.com/150x150/ff9ff3/ffffff?text=PPTX",
        size: "2.7 MB",
        type: "PPTX",
        width: "",
        height: "",
        createdDate: "2024-01-11",
    },
    {
        id: "6",
        name: "mobile-app-icon.png",
        previewUrl: "https://picsum.photos/512/512?random=6",
        thumbnailUrl: "https://picsum.photos/150/150?random=6",
        size: "156 KB",
        type: "PNG",
        width: "512",
        height: "512",
        createdDate: "2024-01-10",
    },
    {
        id: "7",
        name: "video-demo.mp4",
        previewUrl: "https://via.placeholder.com/150x150/54a0ff/ffffff?text=MP4",
        thumbnailUrl: "https://via.placeholder.com/150x150/54a0ff/ffffff?text=MP4",
        size: "15.3 MB",
        type: "MP4",
        width: "1920",
        height: "1080",
        createdDate: "2024-01-09",
    },
    {
        id: "8",
        name: "infographic-chart.png",
        previewUrl: "https://picsum.photos/800/600?random=8",
        thumbnailUrl: "https://picsum.photos/150/150?random=8",
        size: "892 KB",
        type: "PNG",
        width: "800",
        height: "600",
        createdDate: "2024-01-08",
    },
    {
        id: "9",
        name: "brand-guidelines.pdf",
        previewUrl:
            "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
        thumbnailUrl: "https://via.placeholder.com/150x150/5f27cd/ffffff?text=PDF",
        size: "3.4 MB",
        type: "PDF",
        width: "",
        height: "",
        createdDate: "2024-01-07",
    },
    {
        id: "10",
        name: "social-media-post.jpg",
        previewUrl: "https://picsum.photos/1080/1080?random=10",
        thumbnailUrl: "https://picsum.photos/150/150?random=10",
        size: "1.2 MB",
        type: "JPEG",
        width: "1080",
        height: "1080",
        createdDate: "2024-01-06",
    },
    {
        id: "11",
        name: "website-banner.jpg",
        previewUrl: "https://picsum.photos/1200/400?random=11",
        thumbnailUrl: "https://picsum.photos/150/150?random=11",
        size: "2.1 MB",
        type: "JPEG",
        width: "1200",
        height: "400",
        dimensions: { width: 1200, height: 400 },
        createdDate: "2024-01-05",
    },
    {
        id: "12",
        name: "email-template.html",
        previewUrl: "https://via.placeholder.com/150x150/ff6b6b/ffffff?text=HTML",
        thumbnailUrl: "https://via.placeholder.com/150x150/ff6b6b/ffffff?text=HTML",
        size: "15 KB",
        type: "HTML",
        width: "",
        height: "",
        createdDate: "2024-01-04",
    },
    {
        id: "13",
        name: "product-photo.jpg",
        previewUrl: "https://picsum.photos/800/600?random=13",
        thumbnailUrl: "https://picsum.photos/150/150?random=13",
        size: "1.8 MB",
        type: "JPEG",
        width: "800",
        height: "600",
        dimensions: { width: 800, height: 600 },
        createdDate: "2024-01-03",
    },
    {
        id: "14",
        name: "user-manual.pdf",
        previewUrl:
            "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
        thumbnailUrl: "https://via.placeholder.com/150x150/5f27cd/ffffff?text=PDF",
        size: "4.2 MB",
        type: "PDF",
        width: "",
        height: "",
        createdDate: "2024-01-02",
    },
    {
        id: "15",
        name: "app-screenshot.png",
        previewUrl: "https://picsum.photos/400/800?random=15",
        thumbnailUrl: "https://picsum.photos/150/150?random=15",
        size: "890 KB",
        type: "PNG",
        width: "400",
        height: "800",
        createdDate: "2024-01-01",
    },
];

export default mockAssetData;

